-- Comentarios para los campos de CT_Alertas_Configuracion

-- id: Identificador único de la configuración de alerta
-- tipo_alerta_id: Referencia al tipo de alerta (BACKUP, CUENTAS, etc.) desde CT_Alertas_Tipos
-- destinatario_id: Referencia al destinatario que recibirá la alerta desde CT_Alertas_Destinatarios
-- canal_id: Referencia al canal de envío (EMAIL, WHATSAPP, etc.) desde CT_Alertas_Canales
-- tipo_disparo: Tipo de activación de la alerta (PERIODICO, MANUAL, WEBHOOK)
-- frecuencia: Frecuencia de ejecución (DIARIO, SEMANAL, MENSUAL, ANUAL)
-- hora_envio: Hora específica del día para enviar la alerta (formato TIME)
-- dias_semana: Días de la semana para alertas semanales (1=Lun, 2=Mar, etc.) separados por comas
-- dias_mes: Días del mes para alertas mensuales (1-31) separados por comas
-- webhook_id: Referencia opcional al webhook a ejecutar desde CT_Alertas_Webhooks
-- activo: Indica si la configuración está activa (1) o inactiva (0)
-- fecha_creacion: Fecha y hora de creación del registro

-- Ejemplos de valores:
-- tipo_disparo: 'PERIODICO', 'MANUAL', 'WEBHOOK'
-- frecuencia: 'DIARIO', 'SEMANAL', 'MENSUAL', 'ANUAL'
-- dias_semana: '1' (solo lunes), '1,2,3,4,5' (lunes a viernes), '1,3,5' (lun-mié-vie)
-- dias_mes: '1' (primer día), '1,15' (día 1 y 15), '28,29,30,31' (últimos días)
-- hora_envio: '09:00:00', '14:30:00', '23:59:59'